import { storageService } from './storage';
import type { User, Category, Gig } from '@/types/types';

export function initializeData(): void {
  if (storageService.getUsers().length > 0) {
    return;
  }

  const users: User[] = [
    {
      id: 'admin-1',
      email: 'admin@freelancer.com',
      password: 'admin123',
      role: 'admin',
      name: 'Admin User',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
      bio: 'Platform Administrator',
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: false,
      joinedAt: new Date().toISOString(),
    },
    {
      id: 'seller-1',
      email: 'john@example.com',
      password: 'seller123',
      role: 'seller',
      name: 'John Designer',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
      bio: 'Professional graphic designer with 5+ years of experience',
      skills: ['Graphic Design', 'Logo Design', 'Branding', 'Illustration'],
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: false,
      sellerLevel: 'pro',
      successScore: 98,
      totalEarnings: 15000,
      totalOrders: 150,
      isOnline: true,
      vacationMode: false,
      joinedAt: new Date(Date.now() - 365 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'seller-2',
      email: 'sarah@example.com',
      password: 'seller123',
      role: 'seller',
      name: 'Sarah Developer',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
      bio: 'Full-stack developer specializing in React and Node.js',
      skills: ['Web Development', 'React', 'Node.js', 'TypeScript'],
      emailVerified: true,
      phoneVerified: true,
      twoFactorEnabled: false,
      sellerLevel: 'level_2',
      successScore: 95,
      totalEarnings: 12000,
      totalOrders: 80,
      isOnline: true,
      vacationMode: false,
      joinedAt: new Date(Date.now() - 200 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'buyer-1',
      email: 'buyer@example.com',
      password: 'buyer123',
      role: 'buyer',
      name: 'Mike Johnson',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
      bio: 'Entrepreneur looking for quality services',
      emailVerified: true,
      phoneVerified: false,
      twoFactorEnabled: false,
      joinedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  const categories: Category[] = [
    {
      id: 'cat-1',
      name: 'Graphics & Design',
      slug: 'graphics-design',
      icon: '🎨',
      description: 'Logo design, branding, illustrations and more',
    },
    {
      id: 'cat-1-1',
      name: 'Logo Design',
      slug: 'logo-design',
      parentId: 'cat-1',
      description: 'Professional logo design services',
    },
    {
      id: 'cat-1-2',
      name: 'Brand Style Guides',
      slug: 'brand-style-guides',
      parentId: 'cat-1',
      description: 'Complete brand identity packages',
    },
    {
      id: 'cat-2',
      name: 'Programming & Tech',
      slug: 'programming-tech',
      icon: '💻',
      description: 'Web development, mobile apps, and software solutions',
    },
    {
      id: 'cat-2-1',
      name: 'Website Development',
      slug: 'website-development',
      parentId: 'cat-2',
      description: 'Custom website development',
    },
    {
      id: 'cat-2-2',
      name: 'Mobile Apps',
      slug: 'mobile-apps',
      parentId: 'cat-2',
      description: 'iOS and Android app development',
    },
    {
      id: 'cat-3',
      name: 'Digital Marketing',
      slug: 'digital-marketing',
      icon: '📱',
      description: 'SEO, social media, and content marketing',
    },
    {
      id: 'cat-3-1',
      name: 'SEO',
      slug: 'seo',
      parentId: 'cat-3',
      description: 'Search engine optimization services',
    },
    {
      id: 'cat-4',
      name: 'Writing & Translation',
      slug: 'writing-translation',
      icon: '✍️',
      description: 'Content writing, copywriting, and translation',
    },
    {
      id: 'cat-5',
      name: 'Video & Animation',
      slug: 'video-animation',
      icon: '🎬',
      description: 'Video editing, animation, and motion graphics',
    },
  ];

  const gigs: Gig[] = [
    {
      id: 'gig-1',
      sellerId: 'seller-1',
      title: 'I will design a professional logo for your business',
      slug: 'professional-logo-design',
      description: 'Get a unique, professional logo that represents your brand perfectly. I have 5+ years of experience in logo design and have worked with over 500 clients worldwide. Your satisfaction is my priority!',
      categoryId: 'cat-1',
      subcategoryId: 'cat-1-1',
      images: [
        'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1634942537034-2531766767d1?w=800&h=600&fit=crop',
      ],
      pricing: [
        {
          name: 'basic',
          price: 50,
          deliveryDays: 3,
          revisions: 2,
          description: 'Basic logo design',
          features: ['2 initial concepts', '2 revisions', 'High-resolution files', 'Source files'],
        },
        {
          name: 'standard',
          price: 100,
          deliveryDays: 5,
          revisions: 5,
          description: 'Standard package with more options',
          features: ['4 initial concepts', '5 revisions', 'High-resolution files', 'Source files', 'Social media kit'],
        },
        {
          name: 'premium',
          price: 200,
          deliveryDays: 7,
          revisions: 10,
          description: 'Complete branding package',
          features: ['6 initial concepts', 'Unlimited revisions', 'High-resolution files', 'Source files', 'Social media kit', 'Brand style guide'],
        },
      ],
      addOns: [
        { id: 'addon-1', name: 'Extra fast delivery (24h)', price: 30, deliveryDays: 1 },
        { id: 'addon-2', name: '3D mockup', price: 25 },
      ],
      tags: ['logo', 'branding', 'design', 'graphic design'],
      views: 1250,
      clicks: 320,
      orders: 45,
      rating: 4.9,
      reviewCount: 42,
      isActive: true,
      isFeatured: true,
      isSponsored: false,
      createdAt: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'gig-2',
      sellerId: 'seller-2',
      title: 'I will develop a responsive website using React',
      slug: 'react-website-development',
      description: 'Need a modern, fast, and responsive website? I specialize in React development and can create a stunning website tailored to your needs. Clean code, pixel-perfect design, and excellent performance guaranteed!',
      categoryId: 'cat-2',
      subcategoryId: 'cat-2-1',
      images: [
        'https://images.unsplash.com/photo-1547658719-da2b51169166?w=800&h=600&fit=crop',
        'https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800&h=600&fit=crop',
      ],
      pricing: [
        {
          name: 'basic',
          price: 300,
          deliveryDays: 7,
          revisions: 2,
          description: 'Single page website',
          features: ['1 page', 'Responsive design', 'Basic SEO', 'Contact form'],
        },
        {
          name: 'standard',
          price: 600,
          deliveryDays: 14,
          revisions: 4,
          description: 'Multi-page website',
          features: ['Up to 5 pages', 'Responsive design', 'Advanced SEO', 'Contact form', 'CMS integration'],
        },
        {
          name: 'premium',
          price: 1200,
          deliveryDays: 21,
          revisions: 8,
          description: 'Full-featured web application',
          features: ['Up to 10 pages', 'Responsive design', 'Advanced SEO', 'Contact form', 'CMS integration', 'User authentication', 'Database integration'],
        },
      ],
      tags: ['react', 'web development', 'frontend', 'responsive'],
      views: 890,
      clicks: 210,
      orders: 28,
      rating: 4.8,
      reviewCount: 25,
      isActive: true,
      isFeatured: true,
      isSponsored: false,
      createdAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'gig-3',
      sellerId: 'seller-1',
      title: 'I will create a complete brand identity package',
      slug: 'brand-identity-package',
      description: 'Transform your business with a professional brand identity. This package includes logo design, color palette, typography, and brand guidelines to ensure consistency across all your marketing materials.',
      categoryId: 'cat-1',
      subcategoryId: 'cat-1-2',
      images: [
        'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800&h=600&fit=crop',
      ],
      pricing: [
        {
          name: 'basic',
          price: 250,
          deliveryDays: 10,
          revisions: 3,
          description: 'Essential branding',
          features: ['Logo design', 'Color palette', 'Typography selection', 'Basic brand guide'],
        },
        {
          name: 'standard',
          price: 500,
          deliveryDays: 14,
          revisions: 5,
          description: 'Complete branding',
          features: ['Logo design', 'Color palette', 'Typography selection', 'Comprehensive brand guide', 'Business card design', 'Letterhead design'],
        },
        {
          name: 'premium',
          price: 1000,
          deliveryDays: 21,
          revisions: 10,
          description: 'Full brand identity',
          features: ['Logo design', 'Color palette', 'Typography selection', 'Comprehensive brand guide', 'Business card design', 'Letterhead design', 'Social media templates', 'Brand strategy document'],
        },
      ],
      tags: ['branding', 'identity', 'logo', 'design'],
      views: 650,
      clicks: 180,
      orders: 18,
      rating: 5.0,
      reviewCount: 18,
      isActive: true,
      isFeatured: true,
      isSponsored: true,
      createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ];

  storageService.setUsers(users);
  storageService.setCategories(categories);
  storageService.setGigs(gigs);
}
